/**
 * Application de facturation
 * C\'est une application web de genération de facture automatique avec l\'envoie par mail et par whatsapp
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: davidouthe2@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    nom?: string;
    prenom?: string;
    email?: string;
    passwd?: string;
    solde?: number;
    telephone?: string;
    dateNaiss?: string;
    roles?: UserDto.RolesEnum;
}
export namespace UserDto {
    export type RolesEnum = 'USER' | 'ADMIN';
    export const RolesEnum = {
        User: 'USER' as RolesEnum,
        Admin: 'ADMIN' as RolesEnum
    };
}


